import type { ImportField, ImportFieldDefinition } from './types'

export const IMPORT_FIELD_DEFINITIONS: readonly ImportFieldDefinition[] = [
  {
    key: 'deal_id',
    label: 'ID сделки',
    description: 'Уникальный идентификатор сделки в CRM',
    required: true,
    aliases: [
      'deal_id',
      'deal id',
      'deal number',
      'deal no',
      'crm id',
      'id',
      'id сделки',
      'ид сделки',
      'номер сделки',
      'код сделки',
      'идентификатор сделки',
    ],
  },
  {
    key: 'created_at',
    label: 'Дата создания',
    description: 'Дата и время создания сделки',
    required: true,
    aliases: [
      'created_at',
      'created at',
      'created date',
      'creation date',
      'date created',
      'дата создания',
      'создано',
      'дата сделки',
      'дата регистрации',
    ],
  },
  {
    key: 'manager',
    label: 'Менеджер',
    description: 'Ответственный менеджер по сделке',
    required: true,
    aliases: [
      'manager',
      'owner',
      'responsible',
      'assignee',
      'sales manager',
      'salesperson',
      'sales rep',
      'менеджер',
      'ответственный',
      'ответственный менеджер',
      'владелец сделки',
      'сотрудник',
    ],
  },
  {
    key: 'client',
    label: 'Клиент',
    description: 'Название клиента или компании',
    required: true,
    aliases: [
      'client',
      'customer',
      'customer name',
      'company',
      'account',
      'organization',
      'organisation',
      'клиент',
      'компания',
      'контрагент',
      'организация',
      'название клиента',
    ],
  },
  {
    key: 'stage',
    label: 'Этап',
    description: 'Текущий этап воронки или финальный статус',
    required: true,
    aliases: [
      'stage',
      'deal stage',
      'pipeline stage',
      'status',
      'deal status',
      'этап',
      'стадия',
      'статус',
      'этап сделки',
      'стадия сделки',
      'статус сделки',
    ],
  },
  {
    key: 'amount',
    label: 'Сумма',
    description: 'Сумма сделки в рублях',
    required: true,
    aliases: [
      'amount',
      'deal amount',
      'value',
      'deal value',
      'revenue',
      'total',
      'budget',
      'сумма',
      'сумма сделки',
      'бюджет',
      'выручка',
      'стоимость сделки',
      'итого',
    ],
  },
  {
    key: 'last_activity',
    label: 'Последняя активность',
    description: 'Дата последнего контакта или изменения сделки',
    required: false,
    aliases: [
      'last_activity',
      'last activity',
      'last activity at',
      'updated at',
      'last update',
      'modified at',
      'последняя активность',
      'дата активности',
      'последний контакт',
      'дата изменения',
      'обновлено',
    ],
  },
  {
    key: 'closed_at',
    label: 'Дата закрытия',
    description: 'Фактическая дата закрытия сделки',
    required: false,
    aliases: [
      'closed_at',
      'closed at',
      'close date',
      'closed date',
      'won date',
      'дата закрытия',
      'закрыто',
      'дата оплаты',
      'дата завершения',
    ],
  },
  {
    key: 'source',
    label: 'Источник',
    description: 'Канал привлечения сделки',
    required: false,
    aliases: [
      'source',
      'lead source',
      'deal source',
      'channel',
      'acquisition source',
      'источник',
      'источник сделки',
      'канал',
      'канал привлечения',
      'источник лида',
    ],
  },
  {
    key: 'loss_reason',
    label: 'Причина проигрыша',
    description: 'Причина закрытия сделки без продажи',
    required: false,
    aliases: [
      'loss_reason',
      'loss reason',
      'lost reason',
      'failure reason',
      'decline reason',
      'причина проигрыша',
      'причина отказа',
      'причина потери',
      'почему проиграна',
    ],
  },
  {
    key: 'probability',
    label: 'Вероятность',
    description: 'Вероятность закрытия: 0–1 или 0–100%',
    required: false,
    aliases: [
      'probability',
      'close probability',
      'win probability',
      'chance',
      'confidence',
      'вероятность',
      'вероятность закрытия',
      'шанс',
      'процент успеха',
    ],
  },
  {
    key: 'product',
    label: 'Продукт',
    description: 'Продукт или товарная категория',
    required: false,
    aliases: [
      'product',
      'product name',
      'service',
      'sku',
      'category',
      'продукт',
      'товар',
      'услуга',
      'номенклатура',
      'категория продукта',
    ],
  },
  {
    key: 'region',
    label: 'Регион',
    description: 'Регион клиента или сделки',
    required: false,
    aliases: [
      'region',
      'territory',
      'area',
      'location',
      'district',
      'регион',
      'территория',
      'область',
      'город',
      'география',
    ],
  },
] as const

export const IMPORT_FIELD_BY_KEY = Object.fromEntries(
  IMPORT_FIELD_DEFINITIONS.map((field) => [field.key, field]),
) as Record<ImportField, ImportFieldDefinition>
