/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    cases: Case;
    services: Service;
    categories: Category;
    team: Team;
    media: Media;
    enquiries: Enquiry;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    cases: CasesSelect<false> | CasesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Проекты студии. Черновики не видны на сайте, но открываются в предпросмотре.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  title: string;
  /**
   * Указывайте название клиента только с его согласия.
   */
  client: string;
  /**
   * Одно-два предложения для карточки и поиска.
   */
  shortDescription: string;
  /**
   * Показывается в карточке кейса. Необязательно.
   */
  shortResult?: string | null;
  /**
   * Соотношение 4:3. Используется в списке кейсов и в OG.
   */
  cover: number | Media;
  /**
   * Если пусто, используется обложка.
   */
  heroMedia?: (number | null) | Media;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * С чем пришёл клиент. Необязательно — пустой блок не выводится.
   */
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ограничения, рынок, состояние продукта до работы.
   */
  context?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  process?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Свободная часть страницы: изображения, галереи, видео, показатели. Порядок задаётся перетаскиванием.
   */
  contentBlocks?:
    | (
        | RichTextBlock
        | FullWidthImageBlock
        | ImagePairBlock
        | GalleryBlock
        | VideoBlock
        | QuoteBlock
        | MetricGridBlock
        | TextMediaBlock
        | StickyTextBlock
        | NextCaseBlock
      )[]
    | null;
  /**
   * Заполняйте только реальными измеренными данными с указанием источника. Пустой список ничего не выводит.
   */
  metrics?:
    | {
        value: string;
        label: string;
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Публикуйте только настоящие отзывы с согласия автора.
   */
  testimonial?: {
    quote?: string | null;
    author?: string | null;
    role?: string | null;
    photo?: (number | null) | Media;
  };
  projectTeam?:
    | {
        person?: (number | null) | Team;
        externalName?: string | null;
        role: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Что показать в конце страницы. Если не выбрано, подставляется следующий по порядку.
   */
  relatedCase?: (number | null) | Case;
  /**
   * Публичный адрес продукта, если он открыт.
   */
  externalUrl?: string | null;
  /**
   * Если поля пустые, используются название и краткое описание материала, а также OG-изображение по умолчанию из настроек сайта.
   */
  seo?: {
    /**
     * До 70 символов. Показывается во вкладке браузера и в выдаче.
     */
    title?: string | null;
    /**
     * До 180 символов. Текст сниппета в поисковой выдаче.
     */
    description?: string | null;
    /**
     * Оптимальный размер 1200 × 630. Показывается при репосте ссылки.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * Часть адреса страницы. Заполняется автоматически из названия, можно изменить вручную.
   */
  slug: string;
  year: number;
  /**
   * Используется фильтром на странице кейсов.
   */
  services?: (number | Service)[] | null;
  categories?: (number | Category)[] | null;
  /**
   * Избранные кейсы показываются на главной.
   */
  featured?: boolean | null;
  /**
   * Ручная сортировка: меньше — выше в списке. При равных значениях сортировка по дате.
   */
  sortOrder?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Изображения и видео сайта. Для каждого изображения обязателен alt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Что изображено. Для декоративных изображений оставьте пустым и отметьте «Декоративное».
   */
  alt?: string | null;
  /**
   * Скринридер пропустит такое изображение (alt=""). Только для фона и текстур.
   */
  decorative?: boolean | null;
  /**
   * Видимая подпись под изображением в галереях. Необязательно.
   */
  caption?: string | null;
  /**
   * Например: «Фото: Иван Иванов» или условия лицензии.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Короткая метка над текстом. Необязательно.
   */
  eyebrow?: string | null;
  heading?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  width?: ('narrow' | 'wide') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullWidthImageBlock".
 */
export interface FullWidthImageBlock {
  image: number | Media;
  caption?: string | null;
  bleed?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fullWidthImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImagePairBlock".
 */
export interface ImagePairBlock {
  left: number | Media;
  right: number | Media;
  caption?: string | null;
  ratio?: ('equal' | 'left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imagePair';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  heading?: string | null;
  items?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  columns?: ('2' | '3') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  video: number | Media;
  /**
   * Обязателен: показывается до загрузки видео и предотвращает сдвиг вёрстки.
   */
  poster: number | Media;
  caption?: string | null;
  /**
   * Видео зациклится без звука и остановится вне экрана. При prefers-reduced-motion автозапуск отключается.
   */
  autoplay?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  quote: string;
  author?: string | null;
  authorRole?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricGridBlock".
 */
export interface MetricGridBlock {
  /**
   * Например: «Что изменилось».
   */
  heading?: string | null;
  /**
   * Указывайте только измеренные значения и обязательно поясняйте методику. Блок без реальных данных лучше не добавлять.
   */
  metrics?:
    | {
        value: string;
        label: string;
        /**
         * Источник и период. Например: «Яндекс Метрика, 3 месяца после запуска».
         */
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'metricGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextMediaBlock".
 */
export interface TextMediaBlock {
  eyebrow?: string | null;
  heading?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  media: number | Media;
  mediaPosition?: ('right' | 'left') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textMedia';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StickyTextBlock".
 */
export interface StickyTextBlock {
  heading: string;
  intro?: string | null;
  steps?:
    | {
        title: string;
        text: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stickyText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NextCaseBlock".
 */
export interface NextCaseBlock {
  case: number | Case;
  label?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'nextCase';
}
/**
 * Основатели и команда. Имя, роль, биография и фотография редактируются здесь — в коде они не зашиты.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * Часть адреса страницы. Заполняется автоматически из названия, можно изменить вручную.
   */
  slug: string;
  /**
   * Например: «Сооснователь, дизайн» — укажите реальную роль человека.
   */
  role: string;
  /**
   * Портрет 4:5 (вертикальный). Alt-текст задаётся у самого файла в разделе «Медиа».
   */
  photo?: (number | null) | Media;
  /**
   * Одно-два предложения под карточкой. Человеческим языком.
   */
  shortBio?: string | null;
  /**
   * Показывается на странице «О студии». Необязательно.
   */
  extendedBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  quote?: string | null;
  links?:
    | {
        /**
         * Например: Telegram, GitHub, Behance.
         */
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Меньше — раньше в списке.
   */
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Услуги студии, сгруппированные по этапам жизненного цикла проекта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Одна фраза о том, что клиент получает. Без общих слов.
   */
  promise: string;
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * С какими запросами приходят. Формулируйте словами клиента.
   */
  clientProblems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  scope?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  deliverables?:
    | {
        text: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Показываются в блоке услуги. Черновики не выводятся.
   */
  relatedCases?: (number | Case)[] | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  /**
   * Если поля пустые, используются название и краткое описание материала, а также OG-изображение по умолчанию из настроек сайта.
   */
  seo?: {
    /**
     * До 70 символов. Показывается во вкладке браузера и в выдаче.
     */
    title?: string | null;
    /**
     * До 180 символов. Текст сниппета в поисковой выдаче.
     */
    description?: string | null;
    /**
     * Оптимальный размер 1200 × 630. Показывается при репосте ссылки.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * Часть адреса страницы. Заполняется автоматически из названия, можно изменить вручную.
   */
  slug: string;
  /**
   * Этап жизненного цикла. «AI и автоматизация» включайте только если это реальная услуга студии.
   */
  stage: 'research' | 'design' | 'development' | 'growth' | 'ai';
  /**
   * Схематичный знак в карточке услуги.
   */
  icon?: ('signal' | 'grid' | 'layers' | 'path' | 'core') | null;
  /**
   * Необязательно. Заменяет знак в карточке.
   */
  visual?: (number | null) | Media;
  /**
   * Меньше — выше внутри этапа.
   */
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Категории для фильтра на странице кейсов.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Часть адреса страницы. Заполняется автоматически из названия, можно изменить вручную.
   */
  slug: string;
  description?: string | null;
  /**
   * Меньше — выше в списке фильтров.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки с формы на сайте. Создаются автоматически, вручную не заводятся.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  contact: string;
  company?: string | null;
  budget?: string | null;
  message: string;
  status?: ('new' | 'in-progress' | 'closed' | 'spam') | null;
  consent?: boolean | null;
  meta?: {
    sourcePage?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Редактор управляет контентом. Администратор дополнительно управляет пользователями и настройками сайта.
   */
  role: 'admin' | 'editor';
  /**
   * Снимите галочку, чтобы закрыть вход, не удаляя учётную запись.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  shortDescription?: T;
  shortResult?: T;
  cover?: T;
  heroMedia?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  challenge?: T;
  context?: T;
  solution?: T;
  process?: T;
  results?: T;
  contentBlocks?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        fullWidthImage?: T | FullWidthImageBlockSelect<T>;
        imagePair?: T | ImagePairBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        metricGrid?: T | MetricGridBlockSelect<T>;
        textMedia?: T | TextMediaBlockSelect<T>;
        stickyText?: T | StickyTextBlockSelect<T>;
        nextCase?: T | NextCaseBlockSelect<T>;
      };
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        source?: T;
        id?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        photo?: T;
      };
  projectTeam?:
    | T
    | {
        person?: T;
        externalName?: T;
        role?: T;
        id?: T;
      };
  relatedCase?: T;
  externalUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  slug?: T;
  year?: T;
  services?: T;
  categories?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  content?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullWidthImageBlock_select".
 */
export interface FullWidthImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  bleed?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImagePairBlock_select".
 */
export interface ImagePairBlockSelect<T extends boolean = true> {
  left?: T;
  right?: T;
  caption?: T;
  ratio?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  columns?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  video?: T;
  poster?: T;
  caption?: T;
  autoplay?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  authorRole?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricGridBlock_select".
 */
export interface MetricGridBlockSelect<T extends boolean = true> {
  heading?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        source?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextMediaBlock_select".
 */
export interface TextMediaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  content?: T;
  media?: T;
  mediaPosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StickyTextBlock_select".
 */
export interface StickyTextBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NextCaseBlock_select".
 */
export interface NextCaseBlockSelect<T extends boolean = true> {
  case?: T;
  label?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  promise?: T;
  shortDescription?: T;
  fullDescription?: T;
  clientProblems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  scope?:
    | T
    | {
        text?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        text?: T;
        note?: T;
        id?: T;
      };
  relatedCases?: T;
  ctaLabel?: T;
  ctaHref?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  slug?: T;
  stage?: T;
  icon?: T;
  visual?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  photo?: T;
  shortBio?: T;
  extendedBio?: T;
  quote?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  decorative?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  company?: T;
  budget?: T;
  message?: T;
  status?: T;
  consent?: T;
  meta?:
    | T
    | {
        sourcePage?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Оформление, тексты первого экрана, контакты, футер и SEO по умолчанию.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * PNG или SVG с прозрачным фоном. Шапка и подвал тёмные — надпись на логотипе должна быть светлой. Пусто — используется логотип из репозитория.
   */
  logo?: (number | null) | Media;
  /**
   * HEX, например #c9f24a. Приглушённый оттенок для светлых секций и цвет текста на кнопках считаются автоматически.
   */
  accentColor?: string | null;
  siteName: string;
  heroHeading: string;
  heroSubheading: string;
  /**
   * Короткое уточнение. Необязательно.
   */
  heroNote?: string | null;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  positioning?: string | null;
  principles?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  processSteps?:
    | {
        title: string;
        text: string;
        /**
         * Например: «1–2 недели».
         */
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  demoShowcase?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    companyName?: string | null;
    ctaLabel?: string | null;
    note?: string | null;
  };
  contactHeading?: string | null;
  contactText?: string | null;
  /**
   * Пусто — блок email не показывается.
   */
  email?: string | null;
  /**
   * Полный URL, например https://t.me/username. Пусто — не показывается.
   */
  telegram?: string | null;
  /**
   * Пусто — не показывается.
   */
  phone?: string | null;
  city?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  /**
   * Показывается в футере рядом с годом. Необязательно.
   */
  legalName?: string | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  consentText?: string | null;
  /**
   * Если поля пустые, используются название и краткое описание материала, а также OG-изображение по умолчанию из настроек сайта.
   */
  seo?: {
    /**
     * До 70 символов. Показывается во вкладке браузера и в выдаче.
     */
    title?: string | null;
    /**
     * До 180 символов. Текст сниппета в поисковой выдаче.
     */
    description?: string | null;
    /**
     * Оптимальный размер 1200 × 630. Показывается при репосте ссылки.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  organizationDescription?: string | null;
  /**
   * Идентификаторы можно задать здесь или переменными окружения. Пустые значения — скрипты не подключаются.
   */
  analytics?: {
    yandexMetrikaId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Пункты меню в шапке и футере. Меняются без правки кода.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  headerCta?: {
    label?: string | null;
    href?: string | null;
    enabled?: boolean | null;
  };
  footerGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  accentColor?: T;
  siteName?: T;
  heroHeading?: T;
  heroSubheading?: T;
  heroNote?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  positioning?: T;
  principles?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        title?: T;
        text?: T;
        duration?: T;
        id?: T;
      };
  demoShowcase?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        companyName?: T;
        ctaLabel?: T;
        note?: T;
      };
  contactHeading?: T;
  contactText?: T;
  email?: T;
  telegram?: T;
  phone?: T;
  city?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerText?: T;
  legalName?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  consentText?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  organizationDescription?: T;
  analytics?:
    | T
    | {
        yandexMetrikaId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        href?: T;
        enabled?: T;
      };
  footerGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}